# Generated by Django 4.2.7 on 2026-01-09 07:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.CharField(db_index=True, help_text='Hardware Identifier', max_length=100, unique=True)),
                ('api_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('api_key_hash', models.CharField(help_text='Hashed API key', max_length=128)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Latitude, Longitude', null=True, srid=4326)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('retry_limit', models.IntegerField(default=3)),
                ('nid', models.CharField(blank=True, db_index=True, help_text='Network ID', max_length=100, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
    ]
