# Generated by Django 4.2.7 on 2026-01-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
        ('iot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='iot_messages.group'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['api_key'], name='devices_api_key_b48fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['nid'], name='devices_nid_5d6fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['active'], name='devices_active_dfc656_idx'),
        ),
    ]
