# Generated by Django 4.2.7 on 2026-01-10 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users associated with this device (maximum 6 users per Phase 0 spec)', related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
