# Generated by Django 4.2.7 on 2026-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_users_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='city_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='country',
            field=models.CharField(blank=True, default='Canada', help_text='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Device name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='province',
            field=models.CharField(blank=True, help_text='Province/State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sname',
            field=models.CharField(blank=True, help_text='Street name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snumber',
            field=models.CharField(blank=True, help_text='Street number', max_length=20, null=True),
        ),
    ]
