# Generated by Django 4.2.7 on 2026-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_owner_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='api_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Owner API key', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='api_key_hash',
            field=models.CharField(blank=True, help_text='Hashed API key', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='expired',
            field=models.DateField(blank=True, help_text='Account expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='telephone',
            field=models.CharField(blank=True, help_text="Telephone number (also accessible as 'tele')", max_length=20, null=True),
        ),
    ]
