# Generated by Django 4.2.7 on 2026-01-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_owner_group_owner_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='parent_owner',
            field=models.ForeignKey(blank=True, help_text='Parent owner for sub-user accounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='radius_km',
            field=models.FloatField(blank=True, help_text='Routing radius in kilometers for distance-based groups', null=True),
        ),
    ]
