# Generated by Django 4.2.7 on 2026-01-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_type', models.CharField(choices=[('private', 'Private'), ('exclusive', 'Exclusive'), ('open', 'Open'), ('data_logging', 'Data-Logging'), ('enhanced', 'Enhanced'), ('location', 'Location')], max_length=20)),
                ('nid', models.CharField(blank=True, help_text='Network ID', max_length=100, null=True)),
                ('radius', models.FloatField(blank=True, help_text='Radius in kilometers', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('alarm', 'Alarm')], max_length=10)),
                ('alert_type', models.CharField(blank=True, choices=[('sensor', 'Sensor'), ('panic', 'Panic'), ('ns-panic', 'NS-Panic'), ('unknown', 'Unknown'), ('distress', 'Distress')], max_length=20, null=True)),
                ('alarm_type', models.CharField(blank=True, choices=[('pa', 'PA'), ('pm', 'PM'), ('service', 'Service')], max_length=20, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='devices.device')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='devices.device')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_entries', to='iot_messages.message')),
            ],
            options={
                'verbose_name': 'Device Inbox',
                'verbose_name_plural': 'Device Inboxes',
                'db_table': 'device_inbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='device_inbo_device__4102d3_idx'), models.Index(fields=['status', 'created_at'], name='device_inbo_status_0238de_idx')],
                'unique_together': {('device', 'message')},
            },
        ),
    ]
