# Generated by Django 4.2.7 on 2026-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='acknowledge_status',
            field=models.CharField(blank=True, help_text='Acknowledge status (ae) - YES/NO/PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='bcname',
            field=models.CharField(blank=True, help_text='Broadcast name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='co',
            field=models.CharField(blank=True, help_text='Contact/Coordinator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_modified_read',
            field=models.DateTimeField(blank=True, help_text='Last modified read timestamp (lmr)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text='Last read timestamp (lrt)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False, help_text='Message read status'),
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.CharField(blank=True, help_text='Recipient', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.JSONField(default=dict, help_text="Message payload stored as JSON (also accessible as 'msg')"),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text="Message timestamp (also accessible as 'tt')"),
        ),
    ]
